# -*- coding: utf-8 -*-
"""app2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpHOt2J7cNPg2qXC01zGYZwfouoIiMCz
"""

# app1.py
import streamlit as st
def app():
    st.title('APP1')
    st.write('Welcome to app1')