# -*- coding: utf-8 -*-
"""app2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpHOt2J7cNPg2qXC01zGYZwfouoIiMCz
"""

# app2.py
import streamlit as st
import pandas_datareader.data as web
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

now = datetime.now()
date_time = now.strftime("%Y-%m-%d")


def app():
    st.title('Predict')
    st.write('Ticker to predict')


ticker= st.text_input("Ticker", value="Your Ticker")
#source= st.text_input("Source de donnée", value="Yoursource")
#datetime.date(1921, 1, 1)

##### Récupération de donnée

toyota = web.DataReader(ticker, data_source = "yahoo", start = "2013-04-04", end = date_time)

st.line_chart(toyota["Close"])
#st.pyplot(toyota.Close.plot())

#### EN sortie
#( df.tail(2).iloc[0, 0] - df.iloc[0, 0] )/ df.iloc[0, 0]*100

